# The path to steamcmd
steamcmd = ""

# The absolute path to the servers root directory
server = ""

# The process name to monitor
process = ""

# Use Amazon S3 instead of steamcmd, requires that the instance have an assigned IAM role
UseS3Bucket = false

# The bucket name
S3Bucket = ""

# The bucket prefix (not working)
S3BucketPrefix = ""

# The absolute path of the folder to download the server to
S3Folder = ""

# Game folder name
GameFolder = ""

# Game Steam AppID
AppID = ""

# Default game server configuration file URL if none is provided, likely on an S3 Bucket
ServerConfig = ""
